pip install django==2.2.1
pip install psycopg2-binary==2.8.2
pip install django-modeladmin-reorder==0.3.1
pip install django-crispy-forms==1.7.2
pip install paho-mqtt==1.4.0
pip install validators==0.12.5
pip install shortuuid==0.5.0
pip install django-extensions==2.1.6
pip install whitenoise==4.1.2
pip install uwsgi==2.0.18
pip install redis
pip install ipython