# Generated by Django 2.2.1 on 2019-09-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('contents', models.TextField()),
                ('op', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
