# Generated by Django 2.2.1 on 2019-09-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runMES', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmhist',
            old_name='code',
            new_name='alarm_code',
        ),
        migrations.AddField(
            model_name='alarmhist',
            name='set_clear',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
